### ISSUE TITLE
Unable to compile TCP library properly.

### ISSUE THREAD

**Issue by ZLXT** [lvgl/lv_port_xilinx_zedboard_vitis#3]
Hi,guys.
Unable to compile successfully due to TCP library update to V4.00. The problem is that there is a new definition method for the TCP configuration file.
![image](https://github.com/lvgl/lv_port_xilinx_zedboard_vitis/assets/23455922/f0eca13e-eeea-4e79-8403-95ebe65d2309)

Compilation errors can also occur when using V3.1.0, as shown in the following figure.
![image](https://github.com/lvgl/lv_port_xilinx_zedboard_vitis/assets/23455922/16910935-a56c-4d14-bc1a-eab18f7af66c)
![image](https://github.com/lvgl/lv_port_xilinx_zedboard_vitis/assets/23455922/f11d6d6a-9c72-4577-a8cc-fe83bd785651)

I would like to know which version of the TCP library to use, or how to change the TCP configuration file code to adapt to the new veriosn TCP library.

**This is a great project with a practical and rich external library.
I saw a new way to use Vitis to build projects, and I learned a lot from it.
I am a new guy to learning how to use ZYNQ to build embedded systems, and I believe this library can help me a lot.**

In addition.
Do you have any more articles or blogs to introduce the relevant content of this project.
Can you explain how these libraries are ported?

I recently got stuck in LVGL. I have a QSPI interface screen (320 * 386) and use AXI_ DMA transmits data to it, although it can display normally, the frame rate is really too low.
LVGL uses dual buffers and QSPI_ CLK working at 30MHZ, directly control DMA in disp_flush func, transfer (lv_color_t * color_p) to the screen.
The frame rate is only around 20.
I don't know if my code is appropriate.And happen to be able to use this project as a reference.

Thanks.

```
static void disp_flush(lv_disp_drv_t * disp_drv, const lv_area_t * area, lv_color_t * color_p)
{
    int Data_Len = (area->x2 - area->x1 + 1) * (area->y2 - area->y1 + 1) * 2;

    LCD_Set_Window(&QSPI_AXI_Dma, QSPI_BASEADDR, 0x00, area->x1, area->x2, area->y1, area->y2);

    /* param: (DmaDeviceConfig,QspiDeviceAddr,QspiDeviceId,Dma2PLSrcAddr,DataLen) */
    LCD_Write_Pixel(&QSPI_AXI_Dma, QSPI_BASEADDR, 0x00, color_p, Data_Len);
    // usleep(200);
    
    // while(!(QSPI_Read_State(QSPI_BASEADDR) &
    //     DONE_MASK));

    /*IMPORTANT!!!
     *Inform the graphics library that you are ready with the flushing*/
    lv_disp_flush_ready(disp_drv);
}
```
![image](https://github.com/lvgl/lv_port_xilinx_zedboard_vitis/assets/23455922/461c3e12-e668-4d9d-a777-344a350d8b9d)

![IMG_20231007_162610](https://github.com/lvgl/lv_port_xilinx_zedboard_vitis/assets/23455922/3d8224aa-3aa3-4ad9-9881-7c61fc2168e9)

**Comment by kisvegabor** [comment]
Hi,

I cc @pete-pjb, the author if this project.

**Comment by pete-pjb** [comment]
Hi @ZLXT ,

I will update the project for the latest TCP in the next few days, please bear with me as I am busy with my day job right now...
(SEE Comment below now...)

With regard to your low frame rate issue, it is hard to speculate without seeing more detail about your implementation.

Assuming your QSPI interface is definitely clocking at 30 MHz(I would definitely put an oscilloscope on this if possible to make sure) and you have all 4 QSPI data bits enabled you should theoretically be able to achieve a maximum ~101FPS transfer if you are sending 16-bit pixels to the display(The code in your flush suggests you are using 16-bits). 
(320 x 386 pixels = 123520 x 16 bits = 1976320 bits / 4 bit bus = 494080 nibbles / 50MHz = 9.9 mS/Frame =101 FPS)

In reality it is not practical to achieve the full rate but I would expect it to do better certainly...

Have you measured the time it takes to execute the ```LCD_Set_Window()``` and ```LCD_Write_Pixel()``` functions in your flush callback?

You could use the high resolution Zynq timer to get the timings in uS if you are using my port, something like this:
```c
static void disp_flush(lv_disp_drv_t * disp_drv, const lv_area_t * area, lv_color_t * color_p)
{
	uint64_t start_set_win, end_set_win, start_write_pix, end_write_pix;

	int Data_Len = (area->x2 - area->x1 + 1) * (area->y2 - area->y1 + 1) * 2;

	start_set_win = ullGetHighResolutionTime();
	LCD_Set_Window(&QSPI_AXI_Dma, QSPI_BASEADDR, 0x00, area->x1, area->x2, area->y1, area->y2);
	end_set_win = ullGetHighResolutionTime();
	/* param: (DmaDeviceConfig,QspiDeviceAddr,QspiDeviceId,Dma2PLSrcAddr,DataLen) */
	start_write_pix = ullGetHighResolutionTime();
	LCD_Write_Pixel(&QSPI_AXI_Dma, QSPI_BASEADDR, 0x00, color_p, Data_Len);
	end_write_pix = ullGetHighResolutionTime();

	printf( "Start Set Window: %llu uS End Set Window: %llu uS DT:%llu uS\r\n", 
	  start_set_win, end_set_win, end_set_win - start_set_win );
	
	printf( "Start Write Pix: %llu uS End Write: %llu uS DT:%llu uS\r\n",
	  start_write_pix, end_write_pix_win, end_write_pix - start_write_pix );

	// usleep(200);

	// while(!(QSPI_Read_State(QSPI_BASEADDR) &
	//     DONE_MASK));

	/*IMPORTANT!!!
	 *Inform the graphics library that you are ready with the flushing*/
	lv_disp_flush_ready(disp_drv);
}
```

I would suggest measuring these times first to get some idea of where the issue lies, we can then decide where to go next...

Memory caching is also a consideration with Zynq,  I used the write through cache mode on the DMA buffers for my implementation so the cache is always flushed when LVGL updates the buffers.  Then when DMA accesses the memory directly it contains the latest data.  I tested this in the early days of my Zynq port and found write through yielded the best performance for my controller.  I found with no caching enabled on the buffers it was considerably slower.  (I believe this is because when you have dual buffers it speeds up the copies to the other buffer).

With regard to documentation, I haven't  got any I am afraid, the project has evolved over a number of years and I am terrible at documenting things sorry!  If you have any specific questions about the port, please feel free to send me an email at petebone00@gmail.com and I will do my best to answer. 

I hope that helps.

Kind Regards,

Pete

cc: @kisvegabor

**Comment by pete-pjb** [comment]
Hi @ZLXT ,

I have updated the project for the latest version of FreeRTOS +TCP and AMD Vitis/Vivado 2023.1 [here](https://github.com/lvgl/lv_port_xilinx_zedboard_vitis/pull/4).  If you could try and see if it works well for you when you have time and post back here it would be much appreciated.

Kind Regards,

Pete

cc @kisvegabor

**Comment by ZLXT** [comment]
Hi,@pete-pjb .
Sorry for my late reply, because you mentioned that you were busy, so I thought you might need more time.

Thanks for your response and contribution to the open source community.
**I can now compile the project successfully.**
However, before compiling, you also need to change the path specified by `CFG_TUSB_OS_INC_PATH `in `tusb_config.h` to your own FreeRTOS-Kernel/include.
This can be added to README.md

**Comment by pete-pjb** [comment]
Hi @ZLXT ,

No problem, I managed to find a bit of time after I had made the comment... 🙂 

You're very welcome...

Thank you for confirming the project now builds with the latest version of +TCP....

I have added a note in the Readme as you have suggested.

Did you manage to resolve your performance issues?  If I can help please feel free to ask. 

Kind Regards,

Pete

**Comment by ZLXT** [comment]
Hi, @pete-pjb .
Thanks for your concern.

I'm learning about Cache from scratch. And search for problems slowly.

In my project, I just shut down the Cache(`Xil_DCacheDisable();`).This is a bad solution that I know will slow down the reading of DDR data.
I meet issues with cache flusher during DMA transfers.
I didn't have a good solution and didn't know if Cache would cause more problems, so I had to disable it. 

[Here is the link to the question.](https://support.xilinx.com/s/question/0D54U00007PhS0GSAV/axi-dma-loop-example-cache-flush-error-?language=en_US)

I recently looked at several projects including this one, and I decided to go back to using Cache.
So I'm learning about it.

If I have difficulties, I will email you for advice.

Thanks again.
